[pt-br]
    locale    = "pt-br"
    label     = "Português Brasil"
    direction = "ltr"
    title     = "Universitas"
    weight    = 1
    [pt-br.params.sidebar]
        subtitle = "Pesquisa, Análise de Dados & Desenvolvimento Web"

[en]
    locale    = "en"
    label     = "English"
    direction = "ltr"
    title     = "Universitas"
    weight            = 2
    [en.params.sidebar]
        subtitle = "Research, Data Analysis & Web Development"